// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izvmzxnjbfhxtzulxfxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6dm16eG5qYmZoeHR6dWx4ZnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2ODU0OTEsImV4cCI6MjA1MjI2MTQ5MX0.Yksb8QEZQxPLs2kCX21wLd50b-F8CRTZQf4ey-plbRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);